### ISSUE TITLE
Operator Resolution Order

### ISSUE THREAD

**Issue by the-maldridge** [hashicorp/go-bexpr#20]
I'm interested in using this library to filter large amounts of candidates efficiently, but there doesn't seem from my initial reading to be any support for using parenthesis to control the evaluation order.  Is there any support or workaround for order-sensitive evaluations?

**Comment by mkeeler** [comment]
@the-maldridge You can use parentheses with the usual precedence ordering:

This is where we implement it in the grammar:
https://github.com/hashicorp/go-bexpr/blob/18764dbbc60811f03b1cd15681303c4a641805f8/grammar/grammar.peg#L53

And here is an example of where we are testing parentheses override the normal operator precedence:

https://github.com/hashicorp/go-bexpr/blob/18764dbbc60811f03b1cd15681303c4a641805f8/grammar/grammar_test.go#L175-L190

**Comment by the-maldridge** [comment]
Fantastic, thanks for the speedy reply and clear explanation!  I must admit I'm not particularly familiar with peg files so I'll have to take your word for it that that's what that does in the grammar.
