### ISSUE TITLE
If a string starts from a number, then error occurs

### ISSUE THREAD

**Issue by Kasen** [hashicorp/go-bexpr#8]
filter example: `"bar.y == 2bar"`
error: `1:11 (10): rule "number": Invalid number literal`

**Comment by mkeeler** [comment]
@Kasen You will need to quote `2bar` in that filter. Either of the following should work.

```
bar.y == "2bar"

bar.y == `2bar`
```

The only values that can be used unquoted are identifiers (`[a-zA-Z][a-zA-Z0-9_]*`) or numbers (positive and negative integers or floating point).

**Comment by Kasen** [comment]
I had faced it in the consul filtering and had tried single quotes, only. But backquotes(`) have helped me. Thank you.
